export const academicFaculties = [
  {
    id: "engineering",
    label: "Engineering",
    name: "Faculty of Engineering",
    short: "Robotics, energy, transport, sensing, water infrastructure, and civic systems engineering.",
    dean: "Dr. Marko Ilic",
    office: "Intelligent Infrastructure Studio",
    metric: "7 degree pathways",
    email: "engineering@pu.edu.rs",
    programs: ["Civil and Water Infrastructure", "Robotics and Sensing", "Energy Systems", "Transport Systems"],
    labs: ["Systems Prototyping Lab", "Infrastructure Simulation Suite", "Field Robotics Workshop"],
    featuredCourse: "DAT-330 Open Data Studio for Public Dashboards",
    studio: "Students prototype field sensors, infrastructure models, public dashboards, and decision tools with municipal partners.",
    careers: "infrastructure planner, robotics engineer, systems analyst, transport designer"
  },
  {
    id: "computer-science",
    label: "Computer Science",
    name: "School of Computer Science",
    short: "Artificial intelligence, software engineering, cybersecurity, data systems, and public-interest computing.",
    dean: "Luo Zi Chao",
    portrait: {
      fileName: "luo-zi-chao-portrait.jpg",
      alt: "Luo Zi Chao, Dean of the School of Computer Science",
      width: 960,
      height: 1200,
      widths: [360, 720, 960],
      sizes: "(max-width: 680px) 152px, 220px"
    },
    office: "Human-Centered AI and Systems Lab",
    metric: "8 computing pathways",
    email: "computing@pu.edu.rs",
    programs: ["Artificial Intelligence", "Software Engineering", "Cybersecurity", "Data Systems"],
    labs: ["Human-Centered AI Group", "Secure Systems Lab", "Civic Data Interface Lab"],
    featuredCourse: "DAT-330 Open Data Studio for Public Dashboards",
    studio: "Students build auditable AI prototypes, secure software services, reproducible data systems, and public-facing digital tools.",
    careers: "software engineer, AI systems analyst, cybersecurity associate, data product designer"
  },
  {
    id: "land",
    label: "Life Sciences",
    name: "Faculty of Life and Environmental Sciences",
    short: "Agronomy, ecology, food systems, remote sensing, climate adaptation, and water resilience.",
    dean: "Prof. Milena Kovac",
    office: "Water Futures Lab",
    metric: "7 field modules",
    email: "lifesciences@pu.edu.rs",
    programs: ["Climate-Smart Agriculture", "Environmental Biology", "Food Systems", "Water Quality"],
    labs: ["AgriTech Remote Sensing Lab", "Water Futures Lab", "Wetland Habitat Observatory"],
    featuredCourse: "AGT-202 Remote Sensing for Climate-Smart Agriculture",
    studio: "Field teams compare satellite imagery, UAV flights, soil readings, and irrigation notes before writing farm-facing briefs.",
    careers: "agronomist, environmental analyst, water specialist, conservation officer"
  },
  {
    id: "economics",
    label: "Economics",
    name: "School of Economics",
    short: "Regional finance, logistics, entrepreneurship, circular bioeconomy, and responsible growth.",
    dean: "Huang Yu Fei",
    portrait: {
      fileName: "huang-yu-fei-portrait.jpg",
      alt: "Huang Yu Fei, Dean of the School of Economics",
      width: 960,
      height: 1200,
      widths: [360, 720, 960],
      sizes: "(max-width: 680px) 152px, 220px"
    },
    office: "Regional Growth Observatory",
    metric: "4 policy studios",
    email: "economics@pu.edu.rs",
    programs: ["Regional Economics", "Public Finance", "Logistics and Trade", "Sustainable Enterprise"],
    labs: ["Responsible Growth Studio", "Danube Corridor Finance Desk", "Circular Bioeconomy Clinic"],
    featuredCourse: "ECO-220 Regional Economics and Responsible Growth",
    studio: "Students read logistics routes, balance sheets, municipal budgets, and climate-risk scenarios in the same project cycle.",
    careers: "policy analyst, finance associate, logistics planner, development consultant"
  },
  {
    id: "society",
    label: "Society",
    name: "Faculty of Society",
    short: "Anthropology, public policy, media, languages, law, archives, and borderlands heritage.",
    dean: "Chen Wei Hong",
    office: "Borderlands Memory Project",
    metric: "18 oral histories",
    email: "society@pu.edu.rs",
    programs: ["Borderlands Anthropology", "Public Policy", "Media and Communication", "Regional Languages"],
    labs: ["Borderlands Oral History Archive", "Public Service Design Clinic", "Heritage Media Studio"],
    featuredCourse: "ANT-240 Borderlands Ethnography and Oral History",
    studio: "Students practice field interviews, public history, service design, and ethics review with multilingual communities.",
    careers: "researcher, policy officer, archivist, civic media producer"
  },
  {
    id: "health",
    label: "Health",
    name: "Faculty of Health and Human Performance",
    short: "Public health, nutrition, sports science, psychology, and community wellbeing.",
    dean: "Dr. Ana Stojanovic",
    office: "Community Wellbeing Clinic",
    metric: "6 practicum tracks",
    email: "health@pu.edu.rs",
    programs: ["Public Health", "Nutrition", "Sports Science", "Community Psychology"],
    labs: ["Wellbeing Clinic", "Human Performance Lab", "Nutrition Field Kitchen"],
    featuredCourse: "POL-360 Municipal Resilience Policy Clinic",
    studio: "Student teams map service access, heat risk, nutrition support, and wellbeing resources for partner communities.",
    careers: "health coordinator, wellbeing advisor, sports scientist, public service planner"
  },
  {
    id: "graduate",
    label: "Graduate",
    name: "Graduate School",
    short: "Master's and doctoral training with methods, ethics, publication, and mobility support.",
    dean: "Dr. Jelena Maric",
    office: "Applied Research Commons",
    metric: "11 doctoral clusters",
    email: "graduate@pu.edu.rs",
    programs: ["Applied Research Methods", "Doctoral Colloquium", "European Mobility", "Publication Workshop"],
    labs: ["Research Methods Studio", "Ethics Review Desk", "Grant Writing Clinic"],
    featuredCourse: "CAP-404 Capstone Evidence Dossier",
    studio: "Graduate candidates turn fieldwork, datasets, partner questions, and prototypes into defensible public research dossiers.",
    careers: "doctoral researcher, research manager, policy fellow, university lecturer"
  }
];
